---
title: "poker"
author: "Henry Klepper"
output: html_document
---
```{r}
library(dplyr)
library(tidyverse)
```


```{r}
standard_deck <- function(suits = c('C', 'D', 'H', 'S'),
                          ranks = c('2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'),
                          values = seq(2, 14.76, by = 0.25)){
                            
                            deck <- expand.grid(rank = ranks, suit = suits)
                            deck$card <-paste0(deck$rank, deck$suit)
                            
                            deck$suit <- factor(deck$suit, levels = suits, labels = suits)
                            
                            deck <- deck[order(deck$rank, deck$suit), ]
                            
                            deck$value <- values
                            deck$card <- factor(deck$card, levels = deck$card)
                            
                            class(deck) <- c("StandardDeck", "data.frame")
                            
                            return(deck)
                          }
```

```{r}
testdeck = standard_deck()
testdeck
```



```{r}
myDeck = standard_deck()
qDeck = standard_deck()
qDeck = qDeck$value
```






```{r}
drawRandomHand <-function(deck, n = 5){
  x = sample(deck$value, n, replace = FALSE)
  return(x)
}
```

```{r}
buildHandsList <-function(deck, n = 10){
  result = list()
  for(i in 1:n){
    result[[i]] = drawRandomHand(deck)
  }
  
  return(result)
}
```

```{r} 
#Checks if the vector has a pair
vectorCheckPair <- function(vector, only = FALSE){
  #table(vector) returns cards/# card occurences
  #table(table(vector)) returns #card occurences/ card occurence occurences!
  tab = table(table(trunc(vector, 0)))
  if("2" %in% names(tab) | "3" %in% names(tab) | "4" %in% names(tab)){ #I.E, if something occured twice
    
    if(only){
      if(!"3" %in% names(tab) & !"4" %in% names(tab) & tab[2] ==1){ #If ONLY
        return(TRUE)
      } else {
        return(FALSE)
      }
    } else {
      return(TRUE)
    }
  } else {
    return(FALSE)
  }
}
```

```{r}
vectorCheckTwoPair <- function(vector, only = FALSE){
  tab = table(table(trunc(vector, 0)))
  tNames = names(tab)
  
  if("2" %in% tNames){ #Something occured 2x. Options for a 2 pair are 2x2, 2x1 + 3x1. 4x1 does NOT count
    if(tab[2] == 2){ #Case for 2x2
      return(TRUE)
    } else if (!only){ 
      if("3" %in% tNames){ ##i.e, 2x1 + 3x1, Full Houaw
        return(TRUE)
      } else {
        return(FALSE)
      }
    } else { #Not 2x2 and ONLY = True
      return(FALSE)
    }
    
  } else {
    return(FALSE)
  }
}
```

```{r}
vectorCheckThreeKind <-function(vector, only = FALSE){
  tab = table(table(trunc(vector, 0)))
  tNames = names(tab)
  
  if("3" %in% tNames){
    
    if(only){
      if("2" %in% tNames | "4" %in% tNames){
        return(FALSE)
      } else {
        return(TRUE)
      }
    } else {
      return(TRUE)
    }
    
  } else {
    return(FALSE)
  }
}
```

```{r}
vectorCheckFourKind <-function(vector){
  tab = table(table(trunc(vector, 0)))
  tNames = names(tab)
  if("4" %in% tNames){
    return(TRUE)
  } else {
    return(FALSE)
  }
}
```

```{r}
vectorCheckFull <-function(vector){
  tab = table(table(trunc(vector, 0)))
  tNames = names(tab)
  if("3" %in% tNames & "2" %in% tNames){
    return(TRUE)
  } else {
    return(FALSE)
  }
}
```


```{r}
vectorCheckFlush <-function(vector, only = FALSE){
  tab = table(vector%%1)
  if(5 %in% tab){
    
    if(only){
      return(!vectorCheckStraight(vector))
    } else {
      return(TRUE)
    }
  } else {
    return(FALSE)
  }
  
}
```

```{r}
vectorCheckStraight <-function(vector, only = FALSE){
  vec = sort(trunc(vector, 0))
  
  if(all(diff(vec) == 1)){
    
    if(only){
      return(!(vectorCheckFlush(vector)))
    } else {
      return(TRUE)
    }
    
  } else if(14 %in% vec){ #Check for aces low
    vec[5] = 6
    if(all(diff(vec) == 1)){
      return(TRUE)
    } else {
      return(FALSE)
    }
  } else {
    return(FALSE)
  }
}
```

```{r}
vectorCheckStraightFlush <-function(vector, only = FALSE){
  if(vectorCheckStraight(vector) & vectorCheckFlush(vector)){
    if(only){
      return(!vectorCheckRoyalFlush(vector))
    } else {
      return(TRUE)
    }
  } else {
    return(FALSE)
  }
}
```

```{r}
vectorCheckRoyalFlush <-function(vector){
  vec = sort(trunc(vector, 0))
  if(all((vec == c(10, 11, 12, 13, 14)) == TRUE) & vectorCheckFlush(vector)){
    return(TRUE)
  } else {
    return(FALSE)
  }
}
```

```{r}
vectorCheckHighcard <- function(vector){
  if(!vectorCheckPair(vector) & !vectorCheckFlush(vector) & !vectorCheckStraight(vector)){
    return(TRUE)
  } else {
    return(FALSE)
  }
}
```


```{r}
vectorFindHighest <- function(vec, debug = FALSE){
  
  if(debug){
    print(vec)
  }
  
  if(vectorCheckHighcard(vec)){
    vec = (1)
  } else if (vectorCheckPair(vec, only = TRUE)){
    vec = (2)
  } else if (vectorCheckTwoPair(vec, only = TRUE)){
    vec = (3)
  } else if (vectorCheckThreeKind(vec, only = TRUE)){
    vec = (4)
  } else if (vectorCheckStraight(vec, only = TRUE)){
    vec = (5)
  } else if (vectorCheckFlush(vec, only = TRUE)){
    vec = (6)
  } else if (vectorCheckFull(vec)){
    vec = (7)
  } else if (vectorCheckFourKind(vec)){
    vec = (8)
  } else if (vectorCheckStraightFlush(vec, only = TRUE)){
    vec = (9)
  } else if (vectorCheckRoyalFlush(vec)){
    vec = (10)
  } else {
    vec = (0)
  }
  
  
  
}
```

```{r}
interpretOdds <-function(vector){
  print(paste("interpretOdds vector length:", length(vector)))
  tab = table(vector) 
  
  all = length(vector)
  high = ifelse(!is.na(tab[1]), tab[1], 0)
  pairs = ifelse(!is.na(tab[2]), tab[2], 0)
  twopairs = ifelse(!is.na(tab[3]), tab[3], 0)
  threekind = ifelse(!is.na(tab[4]), tab[4], 0)
  straight = ifelse(!is.na(tab[5]), tab[5], 0)
  flush = ifelse(!is.na(tab[6]), tab[6], 0)
  full = ifelse(!is.na(tab[7]), tab[7], 0)
  fourkind = ifelse(!is.na(tab[8]), tab[8], 0) 
  straightflush = ifelse(!is.na(tab[9]), tab[9], 0)
  royal = ifelse(!is.na(tab[10]), tab[10], 0)
  
  print(paste("Highcards:       ", high, "||", high/all * 100, "%", sep = " "))
  print(paste("Pairs:           ", pairs, "||", pairs/all * 100, "%", sep = " "))
  print(paste("Two Pairs:       ", twopairs, "||", twopairs/all * 100, "%", sep = " "))
  print(paste("Three of a Kinds:", threekind, "||", threekind/all * 100, "%", sep = " "))
  print(paste("Straights:       ", straight, "||", straight/all * 100,  "%", sep = " "))
  print(paste("Flushes:         ", flush, "||", flush/all * 100, "%", sep = " "))
  print(paste("Full Houses:     ", full, "||",  full/all * 100, "%", sep = " "))
  print(paste("Four of a Kinds: ", fourkind, "||",  fourkind/all * 100, "%", sep = " "))
  print(paste("Straight Flushes:", straightflush, "||", straightflush/all * 100,  "%", sep = " "))
  print(paste("Royal Flushes:   ", royal, "||", royal/all * 100, "%", sep = " "))
  
  
  
  
}
```

```{r}
simulateHandOdds <-function(list, n, debug = FALSE){

  
  if(debug){
    oddsList = vapply(list, vectorFindHighest, c(result = 0), debug = TRUE)
  } else {
    oddsList = vapply(list, vectorFindHighest, c(result = 0))
  }
  
  
  return(oddsList)
}
```

```{r}
reportSimulation <-function(deck, n){
  
  sHand = buildHandsList(deck, 10000)
  startT = Sys.time()
  simulateHandOdds(sHand, 10000)
  diffT = Sys.time() - startT
  estimated = (n / 10000) * diffT
  
  print(paste("reportSimulationETA:", estimated/60, "minutes"))
  
  sHand = buildHandsList(deck, n)
  sOdds = simulateHandOdds(sHand, n)
  interpretOdds(sOdds)
  return(sOdds)
}
```





```{r}
startingTime = Sys.time()
oods = reportSimulation(myDeck, 2598960)
actualDiff = Sys.time() - startingTime
#"reportSimulationETA: 32.267323037529 minutes"
#"simulateHandOdds ETA: 138.724459567246 minutes"
#"interpretOdds vector length: 2598960"
#"Highcards: 1302954 || 50.1336688521562 %"
#"Pairs: 1097911 || 42.2442438513867 %"
#"Two Pairs: 123691 || 4.75924985378767 %"
#"Three of a Kinds: 54645 || 2.10257179794995 %"
#"Straights: 10167 || 0.391194939514267 %"
#"Flushes: 5145 || 0.197963800904977 %"
#"Full Houses: 3779 || 0.145404315572383 %"
#"Four of a Kinds: 631 || 0.0242789423461692 %"
#"Straight Flushes: 29 || 0.00111583094776372 %"
#"Royal Flushes: 8 || 0.000307815433865854 %"

#"reportSimulationETA: 37.5459875453949 minutes"
#"simulateHandOdds ETA: 173.27983828275 minutes"
#"interpretOdds vector length: 2598960"
#"Highcards: 1303934 || 50.1713762428048 %"
#"Pairs: 1097412 || 42.2250438636993 %"
#"Two Pairs: 123039 || 4.7341628959276 %"
#"Three of a Kinds: 54851 || 2.11049804537199 %"
#"Straights: 10281 || 0.395581309446856 %"
#"Flushes: 4955 || 0.190653184350663 %"
#"Full Houses: 3843 || 0.14786683904331 %"
#"Four of a Kinds: 605 || 0.0232785421861052 %"
#"Straight Flushes: 33 || 0.00126973866469665 %"
#"Royal Flushes: 7 || 0.000269338504632622 %"
```

############# dont look down here
```{r}
#Returns a list(hands = list of hands dealt, cards = array of all cards dealt)
simHandDeals <-function(deck, n = 2){
  cards = sample(deck$value, n*2, replace = FALSE)
  handsList = list()
  
  
  for(i in 1:n){
    handsList[[i]] = c(cards[(1+((i-1)*2))], cards[(2+((i-1)*2))])
  }
  results = list(hands = handsList, cards = cards)
  return(results)
}
```

```{r}

whoWins <-function(results, fiveDraw){
  pHands = results[[1]]
  nPlayers = length(pHands)
  scores = vector(length = nPlayers)
  for(i in 1:nPlayers){
    
    full = vector(length = 7)
    for(j in 1:2){
      vector[j] = pHands[[i]][j]
    }
    print(full)
    scores[i] = vectorFindHighest(full)
  }
  return(scores)
}
```


```{r}
whoWins(devResults, devFive)
```


```{r}
devFive = drawRandomHand(myDeck, 5)
devResults = simHandDeals(myDeck)
devFive
devResults[1]
```
```{r}
head(devResults[[1]][1][1])
```




```{r}
calculateOdds <-function(results){
  hands = results[[1]]
  players = vector(length = length(hands))
  cards = results[[2]]
  newDeck = standard_deck()
  newDeck = newDeck$card
  newDeck = newDeck[!newDeck %in% cards]
  potentialDraws = combn(newDeck, 5, simplify = FALSE)
  nOutcomes = length(potentialDraws)
}
```

